default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  database: buzz
  username: root
  password:


development:
  <<: *default


test:
  <<: *default
  database: buzz_test


production:
  <<: *default